/*
 * SPDX-FileCopyrightText: 2022-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_ASSETS_FILES           12
#define MMAP_ASSETS_CHECKSUM        0xA8E2

enum MMAP_ASSETS_LISTS {
    MMAP_ASSETS_AFRAID_GIF = 0,        /*!< Afraid.gif */
    MMAP_ASSETS_CRY_GIF = 1,        /*!< Cry.gif */
    MMAP_ASSETS_DOWN_GIF = 2,        /*!< Down.gif */
    MMAP_ASSETS_EASY_GIF = 3,        /*!< Easy.gif */
    MMAP_ASSETS_GO_GIF = 4,        /*!< Go.gif */
    MMAP_ASSETS_HAPPY_GIF = 5,        /*!< Happy.gif */
    MMAP_ASSETS_NICE_GIF = 6,        /*!< Nice.gif */
    MMAP_ASSETS_NICE_JOB_GIF = 7,        /*!< Nice_job.gif */
    MMAP_ASSETS_SORRY_GIF = 8,        /*!< Sorry.gif */
    MMAP_ASSETS_THANKS_GIF = 9,        /*!< Thanks.gif */
    MMAP_ASSETS_THINKING_GIF = 10,        /*!< Thinking.gif */
    MMAP_ASSETS_YES_GIF = 11,        /*!< Yes.gif */
};
